---
title: "Data Manipulation"
output: github_document
---

```{r setup}
library(tidyverse)
```

## load in the FAS Litters Data

```{r}
litters_df = 
  read_csv("./data/FAS_litters.csv", na = c("NA", ".", ""))
litters_df = 
  janitor::clean_names(litters_df)

pups_df =
  read_csv("data/FAS_pups.csv", skip = 3, na = c("NA", ".", ""))
pups_df = 
  janitor::clean_names(pups_df)
```

## `select`

Choose some columns and not others.

select 
```{r}
select(litters_df, group, litter_number, gd0_weight)
```

select a range

```{r}
select(litters_df, group, gd0_weight:gd_of_birth)
```

select by removal

```{r}
select(litters_df, -litter_number)
```

Renaming columns ...

```{r}
select(litters_df, GROUP = group, everything())
```

```{r}
rename(litters_df, GROUP = group)
```

Select by prefix

```{r}
select(litters_df, group, starts_with("gd"))
```

rearrange by selecting

```{r}
select(litters_df, starts_with("gd"), group)
```

```{r}
select(litters_df, litter_number, everything())
```

```{r}
relocate(litters_df, litter_number)
```

what if i only select one variable ...?

```{r}
select(litters_df,group)
pull(litters_df, group)
litters_df$group
```

## assessment

```{r}
select(pups_df, litter_number, sex, pd_ears)
```

## `filter`

```{r}
filter(litters_df, gd0_weight < 22)
```

```{r}
filter(litters_df, gd0_weight >= 22)
```

```{r}
filter(litters_df, gd_of_birth == 20)
```

```{r}
filter(litters_df, gd0_weight >= 22, gd_of_birth == 20)
```

```{r}
filter(litters_df, group == "Mod8")
```

```{r}
filter(litters_df, group %in% c("Con7", "Mod8"))
```

filter out missing
```{r}
drop_na(litters_df)
drop_na(litters_df, gd0_weight)
```

class assessment

```{r}
filter(pups_df, sex == 1)
filter(pups_df, pd_walk < 11, sex == 2)
```

## `mutate`

```{r}
mutate(
  litters_df, 
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group))
```


## `arrange`

```{r}
arrange(litters_df, pups_born_alive)
```


## `%>%`

```{r}
litters_data_row = read_csv("./data/FAS_litters.csv", na = c("NA", ".", ""))
litters_clean_name = janitor::clean_names(litters_data_row)
litters_data_selected = select(litters_clean_name, -pups_survive)
litters_mutated = mutate(litters_data_selected, wt_gain = gd18_weight - gd0_weight)
litters_without_missing = drop_na(litters_mutated, gd0_weight)
```

USE THE PIPE OPERATOR INSTEAD

```{r}
litters_df = 
  read_csv("./data/FAS_litters.csv", na = c("NA", ".", "")) %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(wt_gain = gd18_weight - gd0_weight) %>%
  drop_na(gd0_weight)
```

```{r}
pups_df = 
  read_csv("./data/FAS_pups.csv", skip = 3, na = c("NA", ".", "")) %>%
  janitor::clean_names() %>%
  filter(sex == 1) %>%
  select(-pd_ears) %>%
  mutate(pd_pivot_ge7 = pd_pivot >= 7) %>%
```

```{r}
litters_df |>
  lm(wt_gain ~ gd_of_birth, gd0_weight)
```

